### ISSUE TITLE
First Rates & Outputs

### ISSUE THREAD

**Issue by FMCalisto** [MIMBCD-UI/dataset-uta11-rates#1]
As we can see, the [`dataset/`](dataset/) folder is empty without any rates. These rates are important as they will serve as `outputs` of the prototypes for [UTA11](https://github.com/MIMBCD-UI/meta-private/blob/master/wiki/User-Research.md#test-11-assertive-and-non-assertive-introduction-). For instance, see the [`outputs/`](https://github.com/MIMBCD-UI/prototype-assertive-proactive/tree/main/src/common/outputs) folder of the [`prototype-assertive-proactive`](https://github.com/MIMBCD-UI/prototype-assertive-proactive) repository. Indeed, we will have a session with one of our radiologists, and we need to finish this ASAP.

**Comment by JGMF99** [comment]
Issue solved in commit 94ae94bd9502adb16f644f900b95feea313f2cd1.

**Comment by FMCalisto** [comment]
You are the best!
